version: "3.8"
services:

  localstack:
    image: localstack/localstack:1.3.1
    environment:
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=teste
      - AWS_SECRET_ACCESS_KEY=teste
      - EDGE_PORT=4566
      - SERVICES=s3,events,lambda,dynamodb,kinesis,kinesis-firehose 
      - KINESIS_PROVIDER=kinesalite
      - DATA_DIR=${DATA_DIR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
    ports:
      - '4566-4587:4566-4587'
    volumes:
      - localstack-data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - spaces

volumes:
  localstack-data:
    name: localstack-data
  localdynamo-data:
    name: localdynamo-data

networks:
  spaces:
    name: spaces